courses completed
IPL-UV/IPL-UV.github.io pull request #40
Opened 2024-06-05 08:57 UTC by JulioContrerasH

2024-06-05 09:16 UTC, gherardovarando commented on static/files/courses/Color_Vision.zip
maybe it is better if this files are in the content folder, together with the courses file/directory they belong to

2024-06-05 09:20 UTC, gherardovarando requested changes
I reviewed the changes and proposed some improvements.
Could you also update the README and provide a valid archetype for new course ?

2024-06-05 09:20 UTC, gherardovarando commented on static/files/courses/kernel_course.zip
maybe it is better if this files are in the content folder, together with the courses file/directory they belong to

2024-06-05 09:20 UTC, gherardovarando commented on static/files/courses/ps_2014.pdf
maybe it is better if this files are in the content folder, together with the courses file/directory they belong to

2024-06-05 09:20 UTC, gherardovarando commented on static/files/courses/visual_percept.pptx
maybe it is better if this files are in the content folder, together with the courses file/directory they belong to

2024-06-05 09:20 UTC, gherardovarando commented on static/style/style.css
ok

2024-06-05 09:20 UTC, gherardovarando commented on content/courses/color-vision-colorimetry.md
> +**Course Duration:** 30 hours
maybe course duration and instructor could be part of the info in the frontmatter ?

2024-06-05 09:20 UTC, gherardovarando commented on content/courses/glass-training-material.md
> +**Course Duration:** N/A
maybe course duration and instructor could be part of the info in the frontmatter ?

2024-06-05 09:20 UTC, gherardovarando commented on content/courses/color-vision-colorimetry.md
maybe we should have subfolder for each course

2024-06-05 09:20 UTC, gherardovarando commented on themes/isp_uv/layouts/courses/list.html
ok

2024-06-06 13:42 UTC, JulioContrerasH commented on static/files/courses/Color_Vision.zip
Yes, I agree, but there are very large files that weigh more than 100 MB, such as course zip files, where would it be convenient to store them for download?

2024-06-06 13:43 UTC, JulioContrerasH commented on static/files/courses/Color_Vision.zip
There are several cases where it is not allowed to push

2024-06-06 15:12 UTC, gherardovarando commented on static/files/courses/Color_Vision.zip
I think 100mb files should be still fine with GitHub no ?

2024-06-06 18:20 UTC, JulioContrerasH commented on static/files/courses/Color_Vision.zip
There are errors in your weight upload, and I need to remove them in order to push to GitHub.

2024-06-15 18:45 UTC, merged